### ISSUE TITLE
Fix all links inside articles

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-help#23]
Not sure what the syntax for links should be .. @wski ?

**Comment by wski** [comment]
`<a href="/#/global/article/Center_listings_approveReject_orgSteward/Descriptive+Text">Descriptive text</a>`

**Comment by bhalt** [comment]
fixed in branch fix-article-links

**Comment by jal-vsi** [comment]
Failed links for 'Related Articles': Getting Started with OZONE (Getting Started with OZONE (sub-element)), Understanding HUD (same sub-element), Understanding Center (same sub-element), Understanding Webtop (same sub-element). 
Since all Related Articles seem to have the same problem can the sub-element names 1) be deleted or, 2) not shown as links?
